### ISSUE TITLE
No nationality

### ISSUE THREAD

**Issue by AndKe** [fightforthefuture/battleforthenet-widget#105] opened 2017-07-12 14:43 UTC
Is it only for US citizens ? In the end the stupidity and greed will leak out of US too, so we would like to sign.
On the other hand, if it's expected to be US citizens only, having all kinds of others signing may damage the cause ?
The popup on most sites appear in every country

**Comment by adaol322** [comment] 2017-07-12 15:05
sooo is it for US citizens only, or not?

**Comment by zombimudkip** [comment] 2017-07-12 16:23
Go ahead and file an Express claim on the FCC's website (proceeding #: 17-108). There is a box to tick which says "international". Thank you for the help.

https://www.fcc.gov/ecfs/search/proceedings?q=name:((17-108))

**Comment by mikemorris** [comment] 2017-07-12 16:47
FCC comments are open to all! Dupe of #100

**Closed by mikemorris** 2017-07-12 16:47 UTC
