### ISSUE TITLE
No accepting submissions (with specs)

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#113] opened 2017-07-12 16:51 UTC
Doesn’t seem to be accepting submissions.  Here are my computer and browser specs…..and also please see attachment.
 
OS X
10.12.4
 
Chrome
Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by mikemorris** [comment] 2017-07-12 17:51
Assuming this is a dupe of #111, now fixed.

**Closed by mikemorris** 2017-07-12 17:51 UTC
