### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#110] opened 2017-07-12 16:46 UTC
Hey y’all,

I am getting an error on your website when trying to submit a request. :/

I attached a screen shot. Hope it helps!

Cheers,

![unnamed](https://user-images.githubusercontent.com/15023208/28129092-105723d4-6700-11e7-8090-d8368dc45ce0.png)

**Comment by mikemorris** [comment] 2017-07-12 16:54
Dupe of #111

**Closed by mikemorris** 2017-07-12 16:54 UTC
