### ISSUE TITLE
Mobile site header cover the "X" to close the widget

### ISSUE THREAD

**Issue by jtabish** [fightforthefuture/battleforthenet-widget#101] opened 2017-07-12 13:12 UTC
From a partner: "our mobile site has a header that drops down and covers up the "x" to close the widget. Screen shot attached. Is there anything we can do about this? Obviously I want people to sign up but don't want to force them."
![unnamed](https://user-images.githubusercontent.com/29211877/28119273-13f7bc24-66c9-11e7-890b-8874914372de.png)

**Comment by NLDev** [comment] 2017-07-12 13:23
I'd suggest lowering the z-index of the header, which is currently set to `z-index: 9999;`

**Comment by mikemorris** [comment] 2017-07-12 13:24
I'm not reproducing this in Safari or Chrome at small window sizes or in iOS 10.3 Simulator, our `z-index` is higher (`20000`) - this might be a browser bug with `position: fixed`? Any more details on how to reproduce, what iOS version?

**Comment by jtabish** [comment] 2017-07-12 13:58
Here's their answer:

Using iOS version 10.3.2, Safari. Just loaded the site home page in a private browsing window (to circumvent the once-per-day widget restriction) and got the same issue.

**Comment by mikemorris** [comment] 2017-07-12 16:32
Huh, I just tested in Safari on an iPhone 7 running iOS 10.3.2 by visiting https://www.metalsucks.net in a private tab and the modal appears but I'm not able to reproduce this bug.

**Comment by mikemorris** [comment] 2017-10-16 22:41
Closing this as couldn't reproduce.

**Closed by mikemorris** 2017-10-16 22:41 UTC
