### ISSUE TITLE
"Send Letter" button out of place on Safari.

### ISSUE THREAD

**Issue by jtabish** [fightforthefuture/battleforthenet-widget#75] opened 2017-07-10 21:15 UTC
From BitTorrent: 

Can you pass along this issue that we're seeing on our end in Safari? The "Send Letter" button is out of place (see included image). We verified that this occurs on the demo site as well, at https://widget.battleforthenet.com/demos/modal.html.

![send-letter-button](https://user-images.githubusercontent.com/29211877/28040273-2597d7a2-657a-11e7-8b2e-a2117f4e5806.png)

**Comment by jtabish** [comment] 2017-07-10 22:10
Safari Version 9.1.2 (11601.7.7)

**Comment by mikemorris** [comment] 2017-07-10 22:18
I couldn't reproduce this in Safari Version 10.1.1 (12603.2.4) (renders as expected), but the tweaks in https://github.com/fightforthefuture/battleforthenet-widget/commit/c5b3119be2d02667b6acb17ebf175704c9922ca9 may have fixed this regardless. Could you have them check again?

**Comment by twilmoth** [comment] 2017-07-10 23:17
Thanks for looking into this; it seems to have gotten worse:
<img width="1352" alt="bftn-safari-issue-2" src="https://user-images.githubusercontent.com/2184730/28044213-e8e7a308-658a-11e7-991f-6cd61e645bb6.png">

**Comment by mikemorris** [comment] 2017-07-11 04:33
What version of Safari and operating system are you seeing this behavior on @twilmoth? A pull request fixing this would be much appreciated, as I'm not currently able to reproduce this.

**Comment by mikemorris** [comment] 2017-07-11 14:29
More details in #79, closing this to track there instead.

**Closed by mikemorris** 2017-07-11 14:29 UTC
Labels: bug
