### ISSUE TITLE
unable to submit

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#109] opened 2017-07-12 16:44 UTC
I'm unable to submit the filled out form on battleforthenet.com. It fails with a generic error message "There was an error submitting the form, please try again.". No ad block, no javascript block, tried from two PCs, Chrome, IE, and Edge. Same issue.

I suspect the issue is my long email address, 33 characters is long, but you should at least be using a 50 character field on your database for storing emails.

**Comment by mikemorris** [comment] 2017-07-12 16:54
Suspected dupe of #111

**Closed by mikemorris** 2017-07-12 16:54 UTC
