### ISSUE TITLE
People are reporting an error message when they press “send letter” at BattlefortheNet.com

### ISSUE THREAD

**Issue by holmesworcester** [fightforthefuture/battleforthenet-widget#102] opened 2017-07-12 13:47 UTC
Looking into this to see if I can reproduce...

**Comment by holmesworcester** [comment] 2017-07-12 13:49
confirmed, i can reproduce in FF latest.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/213678/28120870-53f77c42-66e7-11e7-993d-8a2a89fb322d.png">

**Comment by holmesworcester** [comment] 2017-07-12 13:49
Confirmed I can reproduce in FF latest.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/213678/28120907-6d7e72b0-66e7-11e7-9bba-9867e10817ae.png">

**Comment by acabey** [comment] 2017-07-12 13:50
Getting that error: 
"There was an error submitting the form, please try again." 

Firefox  54 on Ubuntu 17.04. Comcast business service.

**Comment by holmesworcester** [comment] 2017-07-12 13:50
Console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://queue.fightforthefuture.org/action. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by as-com** [comment] 2017-07-12 13:51
@acabey 
> Comcast business service

Well there's your problem. 😄 

Jokes aside...[CORS all the things](https://enable-cors.org)!

**Comment by acabey** [comment] 2017-07-12 13:53
@as-com 

I didn't want to rule anything out, but it looks like it's a configuration issue anyways. Hopefully this can be fixed earlier rather than later

**Comment by holmesworcester** [comment] 2017-07-12 13:59
It appears fixed now for me. We think this is fixed.

**Comment by acabey** [comment] 2017-07-12 14:10
@holmesworcester 

Confirmed here

**Comment by mikemorris** [comment] 2017-07-12 16:40
Interesting, we didn't make any change to CORS policy this morning. It's possible that CORS headers aren't being set on non-2xx responses.

**Comment by mikemorris** [comment] 2017-07-12 16:41
Also giggling at seeing Cloudflare's version of this widget displaying at https://enable-cors.org/ @as-com 😄

**Comment by mikemorris** [comment] 2017-07-12 16:43
Closing now, as this issue wasn't related to the widget.

**Closed by mikemorris** 2017-07-12 16:43 UTC
