### ISSUE TITLE
Obscured text entry field on iPhone/Chrome

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#62] opened 2017-07-10 15:49 UTC
I tried this on my iPhone using Chrome and when I went to fill in my last name, the window scrolled down to where it says, "Free Press will contact you..." so that I could no longer see where I was typing. The same happened when I went to fill in my address.

**Comment by mikemorris** [comment] 2017-07-10 15:56
This sounds like a dupe of #63

**Closed by mikemorris** 2017-07-10 15:56 UTC
