### ISSUE TITLE
Non-FCC controlled ISPs should be excluded

### ISSUE THREAD

**Issue by doughertym** [fightforthefuture/battleforthenet-widget#144] opened 2017-12-13 12:47 UTC
My ISP (Telekom Deutschland) is not under the FCC's jurisdiction. Therefore, the widget should not be shown for non-FCC controlled ISPs (i.e. anything outside the US).

**Comment by jdc20181** [comment] 2017-12-13 15:16
This project is not just FCC, its a global issue, businesses and website owners in other countries will be impacted by this. There is  already a solution: #121  to this issue, which was addressed.

**Comment by tarrant** [comment] 2017-12-13 19:55
Regardless of if it is a global issue or not the call to action both as stands and in issue #121 are 100% irrelevant to non-US citizens and residents. Calling congress will do nothing since my member of parliament is not part of congress.

**Comment by xXxToxicBlueDustxXx** [comment] 2017-12-13 23:53
well i¿m from Colombia and there's not any net neutrality tux in Wikipedia its not mention because if everybody know the history of Colombia its a country of "monkeys" that make stupid non sense laws (seriously) its god that they don't know about FCC because the only limited service its the Mobile data that is a boom in Colombia, so for these case is god that popup don't show up (I'm want to contributed but whit a pesky laws and congressman that acts like monkeys discuss about religion, sexual education in children's, they don't have time to discuss about FCC, also if anybody is from Colombia, sorry if this offend you, but that's truth )

**Comment by jclc** [comment] 2017-12-30 21:09
I too live outside USA and all the "contact the congress" forms that are shoved to my face do nothing but waste my time.

**Comment by rubbingalcoholic** [comment] 2017-12-30 21:25
Duplicate of https://github.com/fightforthefuture/battleforthenet-widget/issues/145

**Closed by rubbingalcoholic** 2017-12-30 21:25 UTC
