### ISSUE TITLE
text boxes overrun the pop-up

### ISSUE THREAD

**Issue by MXAble** [fightforthefuture/battleforthenet-widget#82] opened 2017-07-11 18:32 UTC
The pop-up itself is tidy, but the text boxes for the petition run off the side of it into the translucent part of the window. Is it supposed to be like that? See screenshot.
![screen shot 2017-07-11 at 2 31 45 pm](https://user-images.githubusercontent.com/30086856/28084166-cd86d1fe-6645-11e7-814e-46339173d4b2.png)

**Comment by mikemorris** [comment] 2017-07-11 20:16
Dupe of #79

**Closed by mikemorris** 2017-07-11 20:16 UTC
